### ISSUE TITLE
Error: unexpected keyward argument 'callback'

### ISSUE THREAD

**Issue by Scrappy996** [RLBot/RLBot#655] opened 2024-11-21 01:53 UTC
![17321539568768580872371828844953](https://github.com/user-attachments/assets/7f5d3b10-87ac-4b51-8807-616feecdd824)

**Comment by Scrappy996** [comment] 2024-11-21 01:53
RL Launcher will not open

**Comment by Sean-Carrick** [comment] 2024-11-21 06:18
Same here, exact same error message. I use RLbot a few times a week and this just started today!

**Comment by Rahail22** [comment] 2024-11-21 15:37
Hi, I have the same issue; I assume it's because of an update. I tried using the offline version, but it did not work. I'm not sure if there is a workaround yet or if we have to wait for an update.

**Comment by swz-git** [comment] 2024-11-21 15:41
Duplicate of https://github.com/RLBot/RLBotGUI/issues/233

**Closed as not planned by swz-git** 2024-11-21 15:41 UTC
