### ISSUE TITLE
bCanDodge - Provide a flag in the data packet which is true when the player is able to air dodge. False when bOnGround is true. False when jump timer has expired. False when bDoubleJumped is true.

### ISSUE THREAD

**Issue by dtracers** [RLBot/RLBot#101] opened 2018-05-31 04:25 UTC

**Comment by nevercast** [comment] 2018-12-06 05:12
Duplicate of #33 ?

**Comment by ddthj** [comment] 2020-06-01 00:59
Stale, and duplicate of #33

**Closed by ddthj** 2020-06-01 00:59 UTC
Labels: enhancement
